### ISSUE TITLE
MetricValue is isize but could be f64

### ISSUE THREAD

**Issue by mike1703** [fralalonde/dipstick#87]
I noticed that dipstick is relying on isize for processing metric values:
https://github.com/fralalonde/dipstick/blob/87af3724f150bdc3ef6a101eeb5a2519af574557/src/lib.rs#L113

Is there a specific reason for this limitation?
At least Graphite and as far as I see Prometheus uses doubles. If one of the output targets would not compatible with non-int datatypes, the conversion to isize could also be moved to the output.
As this is currently limited at the input already limited this is not possible.

Gauge as an example:
https://github.com/fralalonde/dipstick/blob/87af3724f150bdc3ef6a101eeb5a2519af574557/src/input.rs#L205-L210

**Comment by fralalonde** [comment]
Mainly because sources of data (counters, gauges, timers) only provide discrete values: nanoseconds, even count, byte count, etc. 

Also, integer handling is simpler and faster than float, so we stick with it until we derive stats from the collected metrics (rates, etc) at which point float makes sense:

https://github.com/fralalonde/dipstick/blob/87af3724f150bdc3ef6a101eeb5a2519af574557/src/stats.rs#L19

**Comment by fralalonde** [comment]
Ah, I understand what you want to do and why you'd like floats. It's a use case that's somewhat outside the scope of Dipstick, since the metrics you'll be capturing are not "application" metrics but rather external measurements from the physical world. 


The choice of isize was very deliberate and at this point I would not change the existing collection API. Introducing a second API using floats would be possible I guess? Like FloatGauge and FloatTimer, etc. But would also require it's own Stats... At which point it becomes a different project altogether.

So, If you need the whole Dipstick stack you could fork the project and adapt it to suit you needs (starting with MetricValue = f64 or f32). Alternately you could just use / copy the GraphiteOutput and compute the stats on the Graphite side after ingestion.

**Comment by mike1703** [comment]
Ok, thank you for the reasoning. I don't actually need the full dipstick stack but wanted to leverage the nice architecture.
I will probably either continue the search or create a lightweight Graphite implementation of my own given the easy protocol.
